### ISSUE TITLE
Expected execution times of Angha's function extractor

### ISSUE THREAD

**Issue by jordiae** [lac-dcc/Angha#1]
Hi! Thanks for your work. I was taking a look at your function extractor and was wondering whether you had any rough estimates on its speed. Currently, I'm using pycparser (https://github.com/eliben/pycparser) for a similar purpose and it is considerably slow for large files. Thanks!

**Comment by pronesto** [comment]
Hi Jordi,

We have some idea of the time that it takes to build a compilable function.
That includes the time to parse the C program, but the bulk of the time is
spent on type reconstruction. See this report:

http://lac.dcc.ufmg.br/pubs/TechReports/LaC_TechReport012020.pdf

"To reach the threshold of 1,000,000 programs, our framework collected code
from 148 repositories. The exact number of compilable programs generated
was 1,044,023, and the entire process took approximately 145 hours to
terminate."

Leandro run a similar experiment to test psyche-C. Take a look into Section
7.2 of this paper:

https://homepages.dcc.ufmg.br/~fernando/publications/papers/LeandroTOPLAS20.pdf

Kind regards,

Fernando

**Comment by jordiae** [comment]
> Hi Jordi, We have some idea of the time that it takes to build a compilable function. That includes the time to parse the C program, but the bulk of the time is spent on type reconstruction. See this report: http://lac.dcc.ufmg.br/pubs/TechReports/LaC_TechReport012020.pdf "To reach the threshold of 1,000,000 programs, our framework collected code from 148 repositories. The exact number of compilable programs generated was 1,044,023, and the entire process took approximately 145 hours to terminate." Leandro run a similar experiment to test psyche-C. Take a look into Section 7.2 of this paper: https://homepages.dcc.ufmg.br/~fernando/publications/papers/LeandroTOPLAS20.pdf Kind regards, Fernando

Thanks! Do you have the specs of the machine that needed 145 hours?

**Comment by pronesto** [comment]
I need to confirm with Breno (cc'ed), but I think it was an Intel(R)
Core(TM) i7-3770 CPU @ 3.40GHz.

@Breno: could you confirm that you did that experiment to measure Angha's
throughput using Hokusai? Did you use multiple cores, or was it a single
core experiment?

Regards,

Fernando

**Comment by brenocfg** [comment]
Yes, that's correct. It was a multiple core experiment, so in general all 8 cores were in use for the entire experiment.

Note that the experiment's runtime includes the time for the constraint solver to perform type reconstruction, which is a significant portion of the total execution time. If we were to consider only function extraction, I suspect the runtime would be considerably shorter!

**Comment by jordiae** [comment]
> Yes, that's correct. It was a multiple core experiment, so in general all 8 cores were in use for the entire experiment.
> 
> Note that the experiment's runtime includes the time for the constraint solver to perform type reconstruction, which is a significant portion of the total execution time. If we were to consider only function extraction, I suspect the runtime would be considerably shorter!

Understood, thanks!
